server:
  port:
    8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d2b35c699a9815e99617
            clientSecret: 6c211c56d447637a37a3c75348aa67cc89b2f329